version: '2'

services:
  postgres:
    image: postgres:11.6
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py makemigrations --noinput &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8333"
    volumes:
      - ./:/code
    ports:
      - "8333:8333"
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
