# Generated by Django 3.1.7 on 2021-07-24 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제된 일시')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('status', models.CharField(choices=[('T', 'Trash'), ('P', 'Published'), ('D', 'Draft'), ('A', 'Admin')], default='P', max_length=2, verbose_name='게시 상태')),
                ('viewed_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='조회 수')),
                ('liked_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='좋아요 수')),
                ('disliked_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='싫어요 수')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='글쓴이')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
