# Generated by Django 3.1.7 on 2021-07-24 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제된 일시')),
                ('point', models.IntegerField(default=0, verbose_name='점수')),
                ('name', models.CharField(choices=[('질문 등록', 'register_question'), ('댓글 채택', 'select_comment'), ('채택받은 댓글', 'selected_comment'), ('회원가입', 'signup'), ('좋아요받은 댓글', 'liked_comment'), ('좋아요받은 질문', 'liked_question'), ('댓글에 대한 좋아요 취소', 'cancle_liked_comment'), ('질문에 대한 좋아요 취소', 'cancle_liked_question')], default='질문 등록', max_length=20, verbose_name='행동')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제된 일시')),
                ('point_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action_trackings.pointrule', verbose_name='규칙')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
