# Generated by Django 3.1.7 on 2021-07-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('action_trackings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontracking',
            name='actionable_id',
            field=models.PositiveIntegerField(null=True, verbose_name='액션 관련 객체 id'),
        ),
        migrations.AddField(
            model_name='actiontracking',
            name='actionable_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='액션 관련 모델'),
        ),
        migrations.AddField(
            model_name='actiontracking',
            name='count',
            field=models.IntegerField(default=1, verbose_name='액션 횟수'),
        ),
        migrations.AlterField(
            model_name='pointrule',
            name='name',
            field=models.CharField(choices=[('회원가입', 'signup'), ('질문 등록', 'register_question'), ('좋아요 받은 질문', 'liked_question'), ('질문에 대한 좋아요 취소', 'cancle_liked_question'), ('질문 조회', 'show_question'), ('좋아요 받은 댓글', 'liked_comment'), ('댓글 채택', 'select_comment'), ('채택받은 댓글', 'selected_comment'), ('댓글에 대한 좋아요 취소', 'cancle_liked_comment')], default='질문 등록', max_length=20, verbose_name='행동'),
        ),
    ]
