# Generated by Django 3.1.7 on 2021-07-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('T', 'Trash'), ('P', 'Published'), ('D', 'Draft'), ('A', 'Admin')], default='P', max_length=2, verbose_name='게시 상태'),
        ),
    ]
