# Generated by Django 3.1.7 on 2021-03-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 날짜')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제된 날짜')),
                ('performed_id', models.PositiveIntegerField(null=True)),
                ('category', models.CharField(blank=True, choices=[('like', '좋아요'), ('dislike', '싫어요')], max_length=8, null=True)),
                ('performed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
