# Generated by Django 3.1.7 on 2021-03-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perform',
            name='category',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'like'), (2, 'dislike')], default=0),
        ),
    ]
