# Generated by Django 3.1.7 on 2021-04-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0003_auto_20210321_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perform',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제된 일시'),
        ),
    ]
