# Generated by Django 3.1.7 on 2021-04-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210322_1516'),
        ('users', '0003_auto_20210321_0922'),
    ]

    operations = [
    ]
