# Generated by Django 3.1.7 on 2021-04-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20210407_1101'),
        ('users', '0004_merge_20210404_0635'),
    ]

    operations = [
    ]
