# Generated by Django 3.1.7 on 2021-04-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20210404_0635'),
        ('users', '0004_merge_20210406_1124'),
    ]

    operations = [
    ]
