# Generated by Django 3.1.7 on 2021-04-17 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_auto_20210323_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univerisity',
            name='name',
            field=models.CharField(max_length=20, verbose_name='대학이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_point',
            field=models.PositiveIntegerField(default=0, verbose_name='총점수'),
        ),
        migrations.AlterField(
            model_name='user',
            name='univerisity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.univerisity', verbose_name='대학'),
        ),
    ]
