# Generated by Django 3.1.7 on 2021-05-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210522_1834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Univerisity',
            new_name='University',
        ),
    ]
