# Generated by Django 3.1.7 on 2021-05-25 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210525_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='univerisity',
            new_name='university',
        ),
    ]
