# Generated by Django 3.1.7 on 2021-03-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True,
                                     serialize=False, verbose_name='ID')
                ),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('status', models.CharField(choices=[
                 ('P', 'Published'), ('D', 'draft'), ('T', 'Trash'), ('A', 'Admin')],
                    default='P', max_length=1, verbose_name='게시 상태')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('selected', models.BooleanField(default=False, verbose_name='채택 여부')),
                ('content', models.TextField(verbose_name='내용')),
                ('status', models.CharField(choices=[
                 ('P', 'Published'), ('D', 'draft'), ('T', 'Trash'), ('A', 'Admin')],
                    default='P', max_length=1, verbose_name='게시 상태')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='replied_comments', to='question.comment', verbose_name='상위 덧글')),
                (
                    'question',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='comments',
                        to='question.question',
                        verbose_name='질문'
                    )
                ),
            ],
        ),
    ]
