# Generated by Django 3.1.7 on 2021-03-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Trash'), (0, 'Published'),
                                      (1, 'draft'), (2, 'Admin')], default=0, verbose_name='게시 상태'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Trash'), (0, 'Published'),
                                      (1, 'draft'), (2, 'Admin')], default=0, verbose_name='게시 상태'),
        ),
    ]
