# Generated by Django 3.1.7 on 2021-03-26 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210326_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='replied_comments',
                to='question.comment',
                verbose_name='상위 덧글'
            ),
        ),
    ]
