# Generated by Django 3.1.7 on 2021-03-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20210326_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('T', 'Trash'), ('P', 'Published'), ('D', 'Draft'),
                                   ('A', 'Admin')], default=0, max_length=2, verbose_name='게시 상태'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('T', 'Trash'), ('P', 'Published'), ('D', 'Draft'),
                                   ('A', 'Admin')], default=0, max_length=2, verbose_name='게시 상태'),
        ),
    ]
