# Generated by Django 3.1.7 on 2021-04-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20210417_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('T', 'Trash'), ('P', 'Published'), ('D', 'Draft'), ('A', 'Admin')], default='P', max_length=2, verbose_name='게시 상태'),
        ),
    ]
