# Generated by Django 3.1.7 on 2021-05-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20210421_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='disliked_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='싫어요 수'),
        ),
        migrations.AddField(
            model_name='question',
            name='liked_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='좋아요 수'),
        ),
        migrations.AddField(
            model_name='question',
            name='viewed_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='조회 수'),
        ),
    ]
