# Generated by Django 3.1.7 on 2021-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20210525_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='disliked_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='싫어요 수'),
        ),
        migrations.AddField(
            model_name='comment',
            name='liked_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='좋아요 수'),
        ),
    ]
