# Generated by Django 3.1.7 on 2021-03-21 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Add_Question', '질문등록'), ('Add_Comment', '댓글 작성'), ('Select_Comment', '댓글 채택'), ('Selected_Commend', '채택받은 댓글'), ('SignUp', '회원가입'), ('Liked_Question', '좋아요받은 질문'), ('error', 'error')], default='error', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.pointrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
