# Generated by Django 3.1.7 on 2021-03-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrule',
            name='point',
            field=models.IntegerField(choices=[(5, 'Add_Question'), (1, 'Add_Comment'), (1, 'Select_Comment'), (5, 'Selected_Commend'), (10, 'SignUp'), (0.5, 'Liked_Question')], default=0),
        ),
        migrations.AlterField(
            model_name='pointrule',
            name='name',
            field=models.CharField(choices=[('질문등록', 'Add_Question'), ('댓글 작성', 'Add_Comment'), ('댓글 채택', 'Select_Comment'), ('채택받은 댓글', 'Selected_Commend'), ('회원가입', 'SignUp'), ('좋아요받은 질문', 'Liked_Question'), ('error', 'error')], default='error', max_length=20),
        ),
    ]
