# Generated by Django 3.1.7 on 2021-04-04 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0, verbose_name='점수')),
                ('name', models.CharField(choices=[('질문 등록', 'register_question'), ('댓글 채택', 'adopt_comment'), ('채택받은 댓글', 'adopted_comment'), ('회원가입', 'signup'), ('좋아요받은 댓글', 'liked_comment'), ('좋아요받은 질문', 'liked_question')], default='질문 등록', max_length=20, verbose_name='행동')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.pointrule', verbose_name='규칙')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
    ]
