# Generated by Django 3.1.7 on 2021-04-07 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='추가된 일시'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제된 일시'),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정된 일시'),
        ),
        migrations.AddField(
            model_name='pointrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='추가된 일시'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointrule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제된 일시'),
        ),
        migrations.AddField(
            model_name='pointrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정된 일시'),
        ),
    ]
