# Generated by Django 3.1.7 on 2021-05-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20210407_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrule',
            name='name',
            field=models.CharField(choices=[('질문 등록', 'register_question'), ('댓글 채택', 'select_comment'), ('채택받은 댓글', 'selected_comment'), ('회원가입', 'signup'), ('좋아요받은 댓글', 'liked_comment'), ('좋아요받은 질문', 'liked_question')], default='질문 등록', max_length=20, verbose_name='행동'),
        ),
    ]
