# Generated by Django 3.1.7 on 2021-05-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20210516_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrule',
            name='name',
            field=models.CharField(choices=[('질문 등록', 'register_question'), ('댓글 채택', 'select_comment'), ('채택받은 댓글', 'selected_comment'), ('회원가입', 'signup'), ('좋아요받은 댓글', 'liked_comment'), ('좋아요받은 질문', 'liked_question'), ('댓글에 대한 좋아요 취소', 'cancle_liked_comment'), ('질문에 대한 좋아요 취소', 'cancle_liked_question')], default='질문 등록', max_length=20, verbose_name='행동'),
        ),
    ]
