# Generated by Django 3.1.7 on 2021-05-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='viewed_count',
            field=models.IntegerField(default=1, verbose_name='조회수'),
        ),
    ]
