# Generated by Django 3.1.7 on 2021-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20210525_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='viewed_id',
            field=models.PositiveIntegerField(null=True, verbose_name='조회한 ID'),
        ),
    ]
